#!/bin/bash

echo "Analyzing Apache log file......."

echo "----VISITOR IPs----"
#Parses Apache Logs in 'combined log format' and sorts out IP addressing and lists by frequency
cut -d ' ' -f1 $1 | sort -n | uniq -c | sort -r | head

echo "----USER-AGENTS----"
#Parses Apache Logs in 'combined log format' and sorts out User-Agent field and lists by frequency
cut -d '"' -f6 $1 | sort -n | uniq -c | sort -r | head
