#!/bin/bash

echo "Analyzing NGINX log file......."

echo "----VISITOR-IPs----"

#Parses NGINX Logs in 'combined log format' and sorts the "$remote_addr" field and lists by frequency
cut -d ' ' -f1 $1 | sort -n | uniq -c | sort -r | head

echo "----USER-AGENTS----"

#Parses NGINX Logs in 'combined log format' and sorts the "$http_user_agent" field and lists by frequency
cut -d '"' -f6 $1 | sort -n | uniq -c | sort -r | head

echo "--------URL--------"

#Parses NGINX Logs in 'combined log format' and sorts the "$request" field and lists by frequency
cut -d '"' -f2 $1 | sort -n | uniq -c | sort -r | head

echo "------REFERER------"

#Parses NGINX Logs in 'combined log format' and sorts the "$http_referer" field and lists by frequency
cut -d '"' -f4 $1 | sort -n | uniq -c | sort -r | head
