#!/bin/bash

for i in {1..10}; \
do curl -svo /dev/null --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36" -H "host: $1" $2 \
-w 'HTTP Status:\t\t%{http_code} \nTime to Connect:\t%{time_connect} \nNS lookup time:\t\t%{time_namelookup} \nPretransfer Time:\t%{time_pretransfer} \nTTFB:\t\t\t%{time_starttransfer} \nTotal:\t\t\t%{time_total} \n\n\n' 2>&1 | \
egrep -i "Cf-|HTTP Status|NS Lookup Time|TTFB|Time to|Total"; done;
